attention_head_size: 4
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 32
hidden_continuous_sizes: {}
hidden_size: 64
learning_rate: 0.001
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 24
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 1
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    bP5DQSMlcUA=
  max_length: null
  method: standard
  method_kwargs: {}
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    9oMttF6eYUA=
  transformation: relu
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- active_power_lag_1
- active_power_lag_10
- active_power_lag_11
- active_power_lag_12
- active_power_lag_13
- active_power_lag_14
- active_power_lag_15
- active_power_lag_16
- active_power_lag_17
- active_power_lag_18
- active_power_lag_19
- active_power_lag_2
- active_power_lag_20
- active_power_lag_21
- active_power_lag_22
- active_power_lag_23
- active_power_lag_24
- active_power_lag_3
- active_power_lag_4
- active_power_lag_5
- active_power_lag_6
- active_power_lag_7
- active_power_lag_8
- active_power_lag_9
- apparent_power
- current
- deg
- dow
- dow_cos
- dow_sin
- feels_like
- feels_like_t+1
- hour
- hour_cos
- hour_sin
- humidity
- month
- power_factor
- pressure
- reactive_power
- speed
- temp
- temp_max
- temp_min
- temp_t+1
- voltage
- weather_desc_clear sky
- weather_desc_drizzle
- weather_desc_few clouds
- weather_desc_fog
- weather_desc_haze
- weather_desc_light intensity drizzle
- weather_desc_light rain
- weather_desc_mist
- weather_desc_moderate rain
- weather_desc_overcast clouds
- weather_desc_scattered clouds
- weather_desc_thunderstorm
- weather_desc_very heavy rain
time_varying_reals_encoder:
- active_power_lag_1
- active_power_lag_10
- active_power_lag_11
- active_power_lag_12
- active_power_lag_13
- active_power_lag_14
- active_power_lag_15
- active_power_lag_16
- active_power_lag_17
- active_power_lag_18
- active_power_lag_19
- active_power_lag_2
- active_power_lag_20
- active_power_lag_21
- active_power_lag_22
- active_power_lag_23
- active_power_lag_24
- active_power_lag_3
- active_power_lag_4
- active_power_lag_5
- active_power_lag_6
- active_power_lag_7
- active_power_lag_8
- active_power_lag_9
- apparent_power
- current
- deg
- dow
- dow_cos
- dow_sin
- feels_like
- feels_like_t+1
- hour
- hour_cos
- hour_sin
- humidity
- month
- power_factor
- pressure
- reactive_power
- speed
- temp
- temp_max
- temp_min
- temp_t+1
- voltage
- weather_desc_clear sky
- weather_desc_drizzle
- weather_desc_few clouds
- weather_desc_fog
- weather_desc_haze
- weather_desc_light intensity drizzle
- weather_desc_light rain
- weather_desc_mist
- weather_desc_moderate rain
- weather_desc_overcast clouds
- weather_desc_scattered clouds
- weather_desc_thunderstorm
- weather_desc_very heavy rain
- active_power
weight_decay: 0.0
x_categoricals: []
x_reals:
- active_power_lag_1
- active_power_lag_10
- active_power_lag_11
- active_power_lag_12
- active_power_lag_13
- active_power_lag_14
- active_power_lag_15
- active_power_lag_16
- active_power_lag_17
- active_power_lag_18
- active_power_lag_19
- active_power_lag_2
- active_power_lag_20
- active_power_lag_21
- active_power_lag_22
- active_power_lag_23
- active_power_lag_24
- active_power_lag_3
- active_power_lag_4
- active_power_lag_5
- active_power_lag_6
- active_power_lag_7
- active_power_lag_8
- active_power_lag_9
- apparent_power
- current
- deg
- dow
- dow_cos
- dow_sin
- feels_like
- feels_like_t+1
- hour
- hour_cos
- hour_sin
- humidity
- month
- power_factor
- pressure
- reactive_power
- speed
- temp
- temp_max
- temp_min
- temp_t+1
- voltage
- weather_desc_clear sky
- weather_desc_drizzle
- weather_desc_few clouds
- weather_desc_fog
- weather_desc_haze
- weather_desc_light intensity drizzle
- weather_desc_light rain
- weather_desc_mist
- weather_desc_moderate rain
- weather_desc_overcast clouds
- weather_desc_scattered clouds
- weather_desc_thunderstorm
- weather_desc_very heavy rain
- active_power
